FROM rhel7:7-released

LABEL maintainer="OpenShift Development <dev@lists.openshift.redhat.com>" \
      com.redhat.component="openshift-eventrouter-docker" \
      name="openshift3/eventrouter" \
      version="v3.7.0" \
      architecture=x86_64

RUN yum-config-manager --enable rhel-7-server-ose-3.7-rpms && \
    yum install -y openshift-eventrouter && \
    yum clean all

USER nobody

CMD ["/bin/sh", "-c", "/usr/bin/eventrouter -v 3 -logtostderr"]
